{
 "title": "Control_Room",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "patrolguard-data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nfrom(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"prison_sensors\")\r\n  |> pivot(\r\n      rowKey: [\"_time\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n    )\r\n\r\n"
    }
   ]
  },
  {
   "title": "People Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"people_count\")\r\n"
    }
   ]
  },
  {
   "title": "Combined Fence Diagnostic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"vib_threshold\")\r\n"
    }
   ]
  },
  {
   "title": "Door State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"door_state\")\r\n"
    }
   ]
  },
  {
   "title": "Vibration(VIB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"vib_value\")\r\n"
    }
   ]
  },
  {
   "title": "Door Open",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"door_open\")\r\n"
    }
   ]
  },
  {
   "title": "PIR motion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"pir_value\")\r\n"
    }
   ]
  },
  {
   "title": "People Count History",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket:\"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"people_count\")\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> yield(name: \"people_count\")\r\n"
    }
   ]
  },
  {
   "title": "Fence Alert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Prison_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"control_room\")\r\n  |> filter(fn: (r) => r._field == \"fence_alert\")\r\n"
    }
   ]
  }
 ]
}